# Generated by Django 4.1 on 2022-08-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("image", models.TextField()),
                ("price", models.IntegerField()),
                ("release_date", models.DateField()),
                ("lte_exists", models.BooleanField()),
                ("slug", models.TextField()),
            ],
        ),
    ]
